### ISSUE TITLE
running GPU error

### ISSUE THREAD

**Issue by tuliobicudo** [gprMax/gprMax#333] opened 2023-01-17 00:25 UTC
Hello!! 
I am trying to use my RTX3080 to run a gprMax model, but the following error occurs.
Someone could help me, please?

![image](https://user-images.githubusercontent.com/115904647/212784372-e7cace00-948e-4a8e-abb1-a5edfb3aebb9.png)

**Comment by craig-warren** [comment] 2023-01-23 17:18
@tuliobicudo can you check you are able to run some of the sample apps/code that is installed with CUDA. That should help us determine whether the issue is specific to gprMax or your CUDA installation.

**Comment by RochardL** [comment] 2023-01-30 15:04
Hello @craig-warren, I have run into the same issue using a RTX3060. I have installed everything according to the latest instructions as well as checked the path variables and done some sample code installed with CUDA according to some other issues I found on github and am still stuck on this problem. 
I have narrowed it down to the problem happening between line 503 and line 511 in model_build_run.py by checking some of your earlier recommendations. Do you have any other ideas I could try ? 

![image](https://user-images.githubusercontent.com/73845621/215513339-f480b59f-e884-443e-a0ff-eb6add4a9563.png)

**Comment by craig-warren** [comment] 2023-02-17 10:04
@tuliobicudo @RochardL can you confirm what versions of Python and nvcc you are using. Have you been able to test a simple pycuda example successfully? e.g. https://github.com/inducer/pycuda/blob/main/examples/demo.py

**Comment by Rushour0** [comment] 2023-03-21 07:03
Hey, @craig-warren same error came up today, should I work on resolving this issue for the higher end GPUs
Mine is a RTX 3060 too

**Comment by Rushour0** [comment] 2023-03-21 07:33
I found think a small fix for the `ctx.pop()` will suffice for the current issue.

For another issue that I found, 
`nvcc --preprocess -w -m32 -Ic:\users\rushikesh patade\.conda\envs\gprmax\lib\site-packages\pycuda\cuda C:\Users\RUSHIK~1\AppData\Local\Temp\tmp4vobotwr.cu --compiler-options -EP`

Here my path has a space in it, so this might be an issue in compiling because the compile fails because of this
![image](https://user-images.githubusercontent.com/72869428/226542328-999ad863-32f2-4b99-95a8-f6390ca394ea.png)

I think it would be better to use a modified pycuda package for this purpose?

**Comment by craig-warren** [comment] 2023-06-27 09:37
@tuliobicudo @RochardL @Rushour0 - any further progress/thoughts on this?

**Comment by beflowerh** [comment] 2023-07-05 14:58
@tuliobicudo i had same problem, but i solved it。you can try: Add the directory where cl.exe resides in the vc directory to the environment variable, find the location first, and then add the path to the environment variable

**Closed** 2023-09-05 08:14 UTC
