### ISSUE TITLE
Error with subgrids/cylinder_fs.py example and PyCharm

### ISSUE THREAD

**Issue by ysx2023** [gprMax/gprMax#367] opened 2023-08-05 02:05 UTC
i copy the file examples\subgrids\cylinder_fs.py into my Pycharm project with interpreter"Python3.11(gprMax-devel)"
![图片](https://github.com/gprMax/gprMax/assets/141306593/a988e8f8-4d78-4d5b-87e8-442f27074edc)
but when run it  error occurs:
Traceback (most recent call last):
  File "D:\DESK\202307\beta\cylinder_fs.py", line 99, in <module>
    gprMax.run(scenes=[scene], n=1, geometry_only=False, outputfile=fn, subgrid=True, autotranslate=True)
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\gprMax.py", line 162, in run
    run_main(args)
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\gprMax.py", line 224, in run_main
    results = context.run()
              ^^^^^^^^^^^^^
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\contexts.py", line 83, in run
    model.solve(solver)
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\model_build_run.py", line 331, in solve
    solver.solve(iterator)
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\solvers.py", line 116, in solve
    self.updates.hsg_2()
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\updates.py", line 64, in hsg_2
    sg_updater.hsg_2()
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\updates.py", line 134, in hsg_2
    precursors.update_magnetic()
  File "D:\Anaconda_install\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\precursor_nodes.py", line 271, in update_magnetic
    if f_i == f_t:
       ^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (21,300) (5,60)

**Comment by craig-warren** [comment] 2023-08-17 15:41
@ysx2023 have just checked this and certainly don't see any issues with the 'cylinder_fs.py' subgrid example. Can I check you are calling it correctly, e.g. `python examples/subgrids/cylinder_fs.py`

**Comment by woiler103** [comment] 2023-08-28 07:51
I am getting this error as well. Maybe it is related to different version of python? I have python 3.11.4. Everything works after commenting lines
`
if f_i == f_t:
  raise ValueError
`
in `precursor_nodes.py`.
 Obviously, this is a bad way to do it :)

**Comment by woiler103** [comment] 2023-09-02 07:10
I get this error too. Are you trying to compare 2 objects with different dimensions in the string `if f_i == f_t:`?

**Comment by ysx2023** [comment] 2023-09-12 08:01
> @ysx2023 have just checked this and certainly don't see any issues with the 'cylinder_fs.py' subgrid example. Can I check you are calling it correctly, e.g. `python examples/subgrids/cylinder_fs.py`
I meet this bug again with python 3.11.5 and `python examples/subgrids/cylinder_fs.py` correctly.Here are my anaconda environment.yml and requirements.txt
[environment.txt](https://github.com/gprMax/gprMax/files/12583874/environment.txt)
[requirements.txt](https://github.com/gprMax/gprMax/files/12583875/requirements.txt)

**Comment by ysx2023** [comment] 2023-09-12 08:06
can you give me your anaconda environment.yml and requirements.txt? I want to check whether there is something wrong with the version of my python or conda packages

**Comment by ysx2023** [comment] 2023-09-12 08:07
> I get this error too. Are you trying to compare 2 objects with different dimensions in the string `if f_i == f_t:`?

sorry , im not

**Comment by craig-warren** [comment] 2023-09-13 11:33
[req.txt](https://github.com/gprMax/gprMax/files/12596870/req.txt)
[env.txt](https://github.com/gprMax/gprMax/files/12596871/env.txt)

**Comment by GGDRriedel** [comment] 2023-09-14 14:18
Same error here, fresh install.

**Comment by craig-warren** [comment] 2023-09-14 15:10
@ysx2023, @woiler103, @GGDRriedel are you all using PyCharm as @ysx2023 mentioned when highlighting the issue initially?

**Comment by ysx2023** [comment] 2023-09-14 15:21
> @ysx2023, @woiler103, @GGDRriedel are you all using PyCharm as @ysx2023 mentioned when highlighting the issue initially?

 i use Anaconda Powershell Prompt to run it and meet the same error,maybe you can use my conda env and req mentioned and try to run it? 
D:\Anaconda\envs\gprMax-devel\python.exe: No module named D:\WORKSPACE\mess\cylinder_fs
(gprMax-devel) PS C:\Users\ACC1> python 'D:\WORKSPACE\mess\cylinder_fs.py'

=== Electromagnetic modelling software based on the Finite-Difference Time-Domain (FDTD) method =======================

    www.gprmax.com   __  __
     __ _ _ __  _ __|  \/  | __ ___  __
    / _` | '_ \| '__| |\/| |/ _` \ \/ /
   | (_| | |_) | |  | |  | | (_| |>  <
    \__, | .__/|_|  |_|  |_|\__,_/_/\_\
    |___/|_|
                     v4.0.0b0 (Càrn Mòr)

 Copyright (C) 2015-2023: The University of Edinburgh, United Kingdom
 Authors: Craig Warren, Antonis Giannopoulos, and John Hartley

 gprMax is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as
  published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 gprMax is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 You should have received a copy of the GNU General Public License along with gprMax.  If not, see
  www.gnu.org/licenses.

LAPTOP-37GCO7UC | LENOVO 83AM | 0 x unknown (8 cores, 16 cores with Hyper-Threading) | 27.7 GiB | Windows 10 (64-bit)
|--->OpenMP: 8 threads

--- Model 1/1, input file: D:\WORKSPACE\mess\cylinder_fs.py -----------------------------------------------------------

Model title: cylinder_fs.py
Spatial discretisation: 0.005 x 0.005 x 0.005m
Domain size: 0.5 x 0.5 x 0.5m (100 x 100 x 100 = 1e+06 cells)
Mode: 3D
Time step (at CFL limit): 9.62917e-12 secs
Time window: 6e-09 secs (625 iterations)
Waveform mypulse of type gaussiandot with maximum amplitude scaling 1, frequency 1.5e+09Hz created.
Hertzian dipole with polarity z at 0.205m, 0.4m, 0.25m, using waveform mypulse created.
Receiver at 0.245m, 0.4m, 0.25m with output component(s) Ex, Ey, Ez, Hx, Hy, Hz created.
Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 5.10346e-10 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_1.vti will be created.
Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 1.51178e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_2.vti will be created.
Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 2.51321e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_3.vti will be created.
Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 3.50502e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_4.vti will be created.
Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 4.50645e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_5.vti will be created.
Geometry view from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, with filename base cylinder_fs created.
[sg] Material water with eps_r=4.9, sigma=0 S/m; mu_r=1, sigma*=0 Ohm/m created.
[sg] Debye disperion added to water with delta_eps_r=73.34, and tau=8.099e-12 secs created.
[sg] Geometry view from 0.215m, 0.24m, 0.1m, to 0.235m, 0.26m, 0.4m, discretisation 0.001m, 0.001m, 0.001m, with filename base cylinder_fs_sg created.
[sg] Cylinder with face centres 0.225m, 0.25m, 0.1m and 0.225m, 0.25m, 0.4m, with radius 0.01m, of material(s) water created, dielectric smoothing is off.

[sg] Ratio: 1:5
[sg] Spatial discretisation: 0.001 x 0.001 x 0.001m
[sg] Extent (working region): 0.215m, 0.24m, 0.1m to 0.23500000000000001m, 0.26m, 0.4m ((20 x 20 x 300 = 120000 cells)
[sg] Time step: 1.92583e-12 secs

Memory required (estimated): ~388.2 MB [main_grid] + ~253.4 MB [sg] + ~65.0 MB overhead = 706.6 MB

PML boundaries [main_grid]: {formulation: HORIPML, order: 1, thickness (cells): 10}
Building PML boundaries [main_grid]: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 461.72it/s]

Building Yee cells [main_grid]: 100%|████████████████████████████████████████████████████| 2/2 [00:00<00:00, 32.51it/s]

Materials [main_grid]:
    │            │         │       │ sigma │ Delta │ tau │ omega │ delta │ gamma │      │ sigma*  │ Dielectric
 ID │ Name       │ Type    │ eps_r │ [S/m] │ eps_r │ [s] │ [Hz]  │ [Hz]  │ [Hz]  │ mu_r │ [Ohm/m] │ smoothable
────┼────────────┼─────────┼───────┼───────┼───────┼─────┼───────┼───────┼───────┼──────┼─────────┼────────────
  0 │ pec        │ builtin │ 1     │ inf   │       │     │       │       │       │ 1    │ 0       │ False
  1 │ free_space │ builtin │ 1     │ 0     │       │     │       │       │       │ 1    │ 0       │ True

Numerical dispersion analysis [main_grid]: estimated largest physical phase-velocity error is -0.94% in material 'free_space' whose wavelength sampled by 10 cells. Maximum significant frequency estimated as 5.48334e+09Hz

PML boundaries [sg]: {formulation: HORIPML, order: 1, thickness (cells): 6}
Building PML boundaries [sg]: 100%|████████████████████████████████████████████████████| 6/6 [00:00<00:00, 2996.29it/s]

Building Yee cells [sg]: 100%|███████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 18.81it/s]

Materials [sg]:
    │            │         │       │ sigma │ Delta   │ tau        │ omega │ delta │ gamma │      │ sigma*  │ Dielectric
 ID │ Name       │ Type    │ eps_r │ [S/m] │ eps_r   │ [s]        │ [Hz]  │ [Hz]  │ [Hz]  │ mu_r │ [Ohm/m] │ smoothable
────┼────────────┼─────────┼───────┼───────┼─────────┼────────────┼───────┼───────┼───────┼──────┼─────────┼────────────  0 │ pec        │ builtin │ 1     │ inf   │         │            │       │       │       │ 1    │ 0       │ False
  1 │ free_space │ builtin │ 1     │ 0     │         │            │       │       │       │ 1    │ 0       │ True
  2 │ water      │ debye   │ 4.9   │ 0     │ 73.3389 │ 8.0994e-12 │       │       │       │ 1    │ 0       │ False

Numerical dispersion analysis [sg] not carried out as no waveform detected.

Output directory: D:\WORKSPACE\mess

Writing geometry view file 1/2, cylinder_fs.vti: 100%|█████████████████████████| 4.00M/4.00M [00:00<00:00, 74.2Mbyte/s]
Writing geometry view file 2/2, cylinder_fs_sg.vti: 100%|████████████████████████| 480k/480k [00:00<00:00, 61.4Mbyte/s]


Model 1/1 on LAPTOP-37GCO7UC with OpenMP backend using 8 thread(s)
|--->:   0%|                                                                                   | 0/625 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\WORKSPACE\mess\cylinder_fs.py", line 99, in <module>
    gprMax.run(scenes=[scene], n=1, geometry_only=False, outputfile=fn, subgrid=True, autotranslate=True)
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\gprMax.py", line 164, in run
    run_main(args)
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\gprMax.py", line 224, in run_main
    results = context.run()
              ^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\contexts.py", line 83, in run
    model.solve(solver)
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\model_build_run.py", line 331, in solve
    solver.solve(iterator)
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\solvers.py", line 116, in solve
    self.updates.hsg_2()
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\updates.py", line 64, in hsg_2
    sg_updater.hsg_2()
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\updates.py", line 134, in hsg_2
    precursors.update_magnetic()
  File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\precursor_nodes.py", line 271, in update_magnetic
    if f_i == f_t:
       ^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (21,300) (5,60)

**Comment by DragonLT** [comment] 2023-09-14 15:45
I also encountered exactly the same issue. 

> > @ysx2023, @woiler103, @GGDRriedel are you all using PyCharm as @ysx2023 mentioned when highlighting the issue initially?
> 
> i use Anaconda Powershell Prompt to run it and meet the same error,maybe you can use my conda env and req mentioned and try to run it? D:\Anaconda\envs\gprMax-devel\python.exe: No module named D:\WORKSPACE\mess\cylinder_fs (gprMax-devel) PS C:\Users\ACC1> python 'D:\WORKSPACE\mess\cylinder_fs.py'
> 
> === Electromagnetic modelling software based on the Finite-Difference Time-Domain (FDTD) method =======================
> 
> ```
> www.gprmax.com   __  __
>  __ _ _ __  _ __|  \/  | __ ___  __
> / _` | '_ \| '__| |\/| |/ _` \ \/ /
> ```
> 
> | (_| | |_) | | | | | | (_| |> < __, | .**/|_| |_| |_|__,_/_/_ |**_/|_| v4.0.0b0 (Càrn Mòr)
> 
> Copyright (C) 2015-2023: The University of Edinburgh, United Kingdom Authors: Craig Warren, Antonis Giannopoulos, and John Hartley
> 
> gprMax is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. gprMax is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with gprMax. If not, see [www.gnu.org/licenses](http://www.gnu.org/licenses).
> 
> LAPTOP-37GCO7UC | LENOVO 83AM | 0 x unknown (8 cores, 16 cores with Hyper-Threading) | 27.7 GiB | Windows 10 (64-bit) |--->OpenMP: 8 threads
> 
> --- Model 1/1, input file: D:\WORKSPACE\mess\cylinder_fs.py -----------------------------------------------------------
> 
> Model title: cylinder_fs.py Spatial discretisation: 0.005 x 0.005 x 0.005m Domain size: 0.5 x 0.5 x 0.5m (100 x 100 x 100 = 1e+06 cells) Mode: 3D Time step (at CFL limit): 9.62917e-12 secs Time window: 6e-09 secs (625 iterations) Waveform mypulse of type gaussiandot with maximum amplitude scaling 1, frequency 1.5e+09Hz created. Hertzian dipole with polarity z at 0.205m, 0.4m, 0.25m, using waveform mypulse created. Receiver at 0.245m, 0.4m, 0.25m with output component(s) Ex, Ey, Ez, Hx, Hy, Hz created. Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 5.10346e-10 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_1.vti will be created. Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 1.51178e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_2.vti will be created. Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 2.51321e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_3.vti will be created. Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 3.50502e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_4.vti will be created. Snapshot from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, at 4.50645e-09 secs with field outputs Ex, Ey, Ez, Hx, Hy, Hz and filename cylinder_fs_5.vti will be created. Geometry view from 0m, 0m, 0m, to 0.5m, 0.5m, 0.5m, discretisation 0.005m, 0.005m, 0.005m, with filename base cylinder_fs created. [sg] Material water with eps_r=4.9, sigma=0 S/m; mu_r=1, sigma*=0 Ohm/m created. [sg] Debye disperion added to water with delta_eps_r=73.34, and tau=8.099e-12 secs created. [sg] Geometry view from 0.215m, 0.24m, 0.1m, to 0.235m, 0.26m, 0.4m, discretisation 0.001m, 0.001m, 0.001m, with filename base cylinder_fs_sg created. [sg] Cylinder with face centres 0.225m, 0.25m, 0.1m and 0.225m, 0.25m, 0.4m, with radius 0.01m, of material(s) water created, dielectric smoothing is off.
> 
> [sg] Ratio: 1:5 [sg] Spatial discretisation: 0.001 x 0.001 x 0.001m [sg] Extent (working region): 0.215m, 0.24m, 0.1m to 0.23500000000000001m, 0.26m, 0.4m ((20 x 20 x 300 = 120000 cells) [sg] Time step: 1.92583e-12 secs
> 
> Memory required (estimated): ~388.2 MB [main_grid] + ~253.4 MB [sg] + ~65.0 MB overhead = 706.6 MB
> 
> PML boundaries [main_grid]: {formulation: HORIPML, order: 1, thickness (cells): 10} Building PML boundaries [main_grid]: 100%|██████████████████████████████████████████████| 6/6 [00:00<00:00, 461.72it/s]
> 
> Building Yee cells [main_grid]: 100%|████████████████████████████████████████████████████| 2/2 [00:00<00:00, 32.51it/s]
> 
> Materials [main_grid]: │ │ │ │ sigma │ Delta │ tau │ omega │ delta │ gamma │ │ sigma* │ Dielectric ID │ Name │ Type │ eps_r │ [S/m] │ eps_r │ [s] │ [Hz] │ [Hz] │ [Hz] │ mu_r │ [Ohm/m] │ smoothable ────┼────────────┼─────────┼───────┼───────┼───────┼─────┼───────┼───────┼───────┼──────┼─────────┼──────────── 0 │ pec │ builtin │ 1 │ inf │ │ │ │ │ │ 1 │ 0 │ False 1 │ free_space │ builtin │ 1 │ 0 │ │ │ │ │ │ 1 │ 0 │ True
> 
> Numerical dispersion analysis [main_grid]: estimated largest physical phase-velocity error is -0.94% in material 'free_space' whose wavelength sampled by 10 cells. Maximum significant frequency estimated as 5.48334e+09Hz
> 
> PML boundaries [sg]: {formulation: HORIPML, order: 1, thickness (cells): 6} Building PML boundaries [sg]: 100%|████████████████████████████████████████████████████| 6/6 [00:00<00:00, 2996.29it/s]
> 
> Building Yee cells [sg]: 100%|███████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 18.81it/s]
> 
> Materials [sg]: │ │ │ │ sigma │ Delta │ tau │ omega │ delta │ gamma │ │ sigma* │ Dielectric ID │ Name │ Type │ eps_r │ [S/m] │ eps_r │ [s] │ [Hz] │ [Hz] │ [Hz] │ mu_r │ [Ohm/m] │ smoothable ────┼────────────┼─────────┼───────┼───────┼─────────┼────────────┼───────┼───────┼───────┼──────┼─────────┼──────────── 0 │ pec │ builtin │ 1 │ inf │ │ │ │ │ │ 1 │ 0 │ False 1 │ free_space │ builtin │ 1 │ 0 │ │ │ │ │ │ 1 │ 0 │ True 2 │ water │ debye │ 4.9 │ 0 │ 73.3389 │ 8.0994e-12 │ │ │ │ 1 │ 0 │ False
> 
> Numerical dispersion analysis [sg] not carried out as no waveform detected.
> 
> Output directory: D:\WORKSPACE\mess
> 
> Writing geometry view file 1/2, cylinder_fs.vti: 100%|█████████████████████████| 4.00M/4.00M [00:00<00:00, 74.2Mbyte/s] Writing geometry view file 2/2, cylinder_fs_sg.vti: 100%|████████████████████████| 480k/480k [00:00<00:00, 61.4Mbyte/s]
> 
> Model 1/1 on LAPTOP-37GCO7UC with OpenMP backend using 8 thread(s) |--->: 0%| | 0/625 [00:00<?, ?it/s] Traceback (most recent call last): File "D:\WORKSPACE\mess\cylinder_fs.py", line 99, in gprMax.run(scenes=[scene], n=1, geometry_only=False, outputfile=fn, subgrid=True, autotranslate=True) File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\gprMax.py", line 164, in run run_main(args) File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\gprMax.py", line 224, in run_main results = context.run() ^^^^^^^^^^^^^ File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\contexts.py", line 83, in run model.solve(solver) File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\model_build_run.py", line 331, in solve solver.solve(iterator) File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\solvers.py", line 116, in solve self.updates.hsg_2() File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\updates.py", line 64, in hsg_2 sg_updater.hsg_2() File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\updates.py", line 134, in hsg_2 precursors.update_magnetic() File "D:\Anaconda\envs\gprMax-devel\Lib\site-packages\gprmax-4.0.0b0-py3.11-win-amd64.egg\gprMax\subgrids\precursor_nodes.py", line 271, in update_magnetic if f_i == f_t: ^^^^^^^^^^ ValueError: operands could not be broadcast together with shapes (21,300) (5,60)

**Comment by DragonLT** [comment] 2023-09-14 15:59
I just downgraded the python version to 3.10.13, but still got the same error.

**Comment by woiler103** [comment] 2023-09-14 16:10
I don't use pycharm. I use Anaconda Prompt to run it. So far I have commented out the lines "if f_i == f_t: raise ValueError" in 'precursor_nodes.py' waiting for a solution to the problem

**Comment by GGDRriedel** [comment] 2023-09-18 08:30
Here is my environment: 
[environment.txt](https://github.com/gprMax/gprMax/files/12645880/environment.txt)

**Comment by craig-warren** [comment] 2023-09-18 15:34
Had a chance to do a little investigating and I can reproduce this error on a fresh install of gprMax on Windows 11, but it does not occur on macOS (13.5.2). Checking environments further.

**Comment by craig-warren** [comment] 2023-09-18 19:28
This was due to numpy == being deprecated with 1.25.0 - https://github.com/numpy/numpy/pull/22707 Fixed by using np.array_equals

**Closed by craig-warren** 2023-09-18 19:28 UTC
Labels: v4 bug
