### ISSUE TITLE
Some suggestions for initialization

### ISSUE THREAD

**Issue by realbili** [gprMax/gprMax#428] opened 2024-03-07 19:06 UTC
I recently installed and used gprMAX.
I encountered and solved some minor problems during the configuration process, and I've documented them for your reference.
Python Version : 3.10 (Anaconda)
OS : Win 11

1.  following the installation [https://docs.gprmax.com/en/latest/include_readme.html](guide), when you run the
`python setup.py build`, problem 
**UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 13936: illegal multibyte sequence**, like #422.
You need chage the file `setup.py` in line 52,  to 'rb'
<img width="677" alt="1709830242467" src="https://github.com/gprMax/gprMax/assets/93770744/7369ba04-d9f7-44c8-ae17-13356199b187">

2. when you finish the 1st problem, u may run `python setup.py install`, here you may conter anohter problem "endswith first arg must be bytes or a tuple of bytes, not str".
You need to change the file called '_core_metadata.py' in your virtual Anaconda env, my Path is this:
<img width="330" alt="1709838048657" src="https://github.com/gprMax/gprMax/assets/93770744/3de52ec5-591b-471b-89d3-c8f5b915bc85">

In this file, line 209, you need add `b` before "\n", like this:
<img width="618" alt="9b475ea9ee24d7e90c58fb0e6bf3373" src="https://github.com/gprMax/gprMax/assets/93770744/e3812fbe-1b29-435c-ba90-2fbe1652406a">

Hope this message can help you enjoy this journey!

**Comment by huntermarchi** [comment] 2024-03-08 22:08
I recently installed and utilized gprMAX on my system running Python 3.10 (Anaconda) on Windows 11. During the installation process outlined in the documentation [link to documentation], I encountered and resolved several minor issues, which I've documented below for your reference:

UnicodeDecodeError during 'python setup.py build':

Issue: Encounter UnicodeDecodeError when decoding README.rst in setup.py.
Solution: Modify setup.py file, line 52, to use 'rb' mode instead of 'r'.
'endswith' TypeError during 'python setup.py install':

Issue: TypeError stating 'endswith' first arg must be bytes or a tuple of bytes, not str.
Solution: Edit '_core_metadata.py' file located in the virtual Anaconda environment. Modify line 209 to add 'b' before "\n".
Your paths may vary based on your specific environment setup.

I hope these solutions help fellow users navigate through the installation process smoothly. If you encounter any further issues or have suggestions for improving the initialization process, please feel free to share them.

Happy gprMAX-ing!

**Comment by craig-warren** [comment] 2024-03-19 11:33
Closing as largely duplicate of https://github.com/gprMax/gprMax/issues/422

**Closed by craig-warren** 2024-03-19 11:33 UTC
