### ISSUE TITLE
Instability in 1D transmission line when resistance > 208 Ohms

### ISSUE THREAD

**Issue by Xianyang-Gao** [gprMax/gprMax#89] opened 2017-01-13 10:37 UTC
I modelled a basic bowtie antenna fed by a transmission line. When I increased the resistance of transmission line to 209 Ohms, the transmission line became unstable but a 208 Ohms transmission line can work well.

I have attached the input file below.

[antenna_bowtie_50x40_200ohms.txt](https://github.com/gprMax/gprMax/files/704057/antenna_bowtie_50x40_200ohms.txt)

Best regards

**Comment by craig-warren** [comment] 2017-01-13 10:48
Thanks @Xianyang-Gao I'll take a look at this sometime next week.

Craig

**Comment by craig-warren** [comment] 2017-02-21 13:27
@Xianyang-Gao This issue should now be resolved in the latest code (v.3.0.17). The instability was being caused by the spatial step (based on the magic time step) that was being used internally in the transmission line.

**Closed by craig-warren** 2017-02-21 13:27 UTC
Labels: bug
