### ISSUE TITLE
The direct waves displayed incompletely. 

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [gprMax/gprMax#286] opened 2021-04-08 03:13 UTC
Hello, I encountered some problems when using gprMax for 3D forward modeling. The direct waves displayed incompletely. Could you please have a look and give me some suggestions? Thank you so much.
![5b0c9dc57cec0545bc7f21715b760a5](https://user-images.githubusercontent.com/55009436/113963042-68cf8680-9818-11eb-985a-ff7abb53ffe5.png)
![6](https://user-images.githubusercontent.com/55009436/113963045-69681d00-9818-11eb-903d-931dfe23db27.jpg)

**Comment by craig-warren** [comment] 2021-04-08 13:19
Duplicate of #285 - please post on our Google Group - https://groups.google.com/g/gprmax

**Closed by craig-warren** 2021-04-08 13:19 UTC
