### ISSUE TITLE
Runing script

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#10] opened 2015-11-21 04:28 UTC
Good morning,
First of all, it is a grrreat work you have been doing! I am really amazed. Congrats!

I was wondering if it was possible to run gprMax not from the Master folder.
I usually that with .py script by adding the interpreter line at the first line of the script, like #!/usr/bin/python3 and then chmod+x the script and adding it to the path.
But it seems it dos not work with gprMax.py as I always get:
SystemError: Parent module '' not loaded, cannot perform relative import

Where do I miss something?

cheers

**Comment by craig-warren** [comment] 2015-11-21 11:24
Hi Eleger,

gprMax was designed to be used as a Python package (with according use of imports) -  https://docs.python.org/3/tutorial/modules.html#packages

**Comment by ELEGER** [comment] 2015-11-22 02:39
Hi Craig,
Thanks for your answer,
Could I propose a sudo python setup.py develop ?
Or it is too dirty to be proposed to users?

Modifying pythonpath and sys.path can as well do the job, but is less automatic or dirtier I'd say.


cheers

emmanuel

**Comment by craig-warren** [comment] 2015-11-22 10:56
I'm not so keen for those solutions. Are they not against the 'zen' of Python ;-)

What might be better is to see if absolute imports would allow you to run it as a script, i.e. change 
`from .constants import e0` to `from gprMax.constants import e0`.

**Comment by craig-warren** [comment] 2015-11-25 16:46
Emmanuel,

I'm going to update everything to use absolute imports, e.g. `from gprMax.constants import e0` in the next few days. I think that because gprMax is designed to operate as a package it has to be run using the `-m` switch, so you can't easily run the main module as a script. I think if users want to do this then we'll leave it to them ;-) therefore I'm going to close this issue.

**Closed by craig-warren** 2015-11-25 16:46 UTC
