### ISSUE TITLE
Segmentation fault when using #fractal_box command

### ISSUE THREAD

**Issue by max-jacobs** [gprMax/gprMax#3] opened 2015-10-13 13:03 UTC
gprMax throws a segmentation fault after the first run when the fractal_box and soil_peplinksi commands are used to create a soil mixture model. This occurs even on the example provided. Any help to solve this would be appreciated as this feature is extremely helpful for our modelling.

Please let me know if more information is needed.

Thanks.

**Comment by p4tr1ckc4rs0n** [comment] 2015-10-13 13:51
I too am getting the same error

**Comment by craig-warren** [comment] 2015-10-13 15:20
Hi max-jacobs and p4tr1ckc4rs0n, 

Thanks for the feedback. If I can get a few more details we should be able to figure our what is causing the issue. Are you attempting to run the `heterogeneous_soil.in` model from the `user_models` sub package? Can you test with `python -m gprMax user_models/heterogeneous_soils.in --geometry-only` and `python -m gprMax user_models/heterogeneous_soils.in` and copy the messages that are printed when you get a segmentation fault? What platform are you using? Windows?

I'm away from the office at the moment so I don't have access to my test machine which has VMs for Windows and Linux. I can't reproduce the issue on my MacBook, `heterogeneous_soil.in` runs OK.

**Comment by max-jacobs** [comment] 2015-10-13 16:07
Hi craig-warren, thanks for your quick response. 

Running `<heterogeneous_soil.in> ` gives this output:

```
Geometry file(s) written in [HH:MM:SS]: 0:00:01

Output to file: ...gprMax/user_models/heterogeneous_soil.out
Estimated runtime [HH:MM:SS]: 0:03:52
Solving for model run 1 of 1...
|##################################################| 100.0%

Solving took [HH:MM:SS]: 0:04:50
Peak memory (approx) used: 349.6 KB
*** Error in `python3': free(): invalid size: 0x00007ff747dde010 ***
Aborted (core dumped)
```

and running with the  `<--geometry-only> ` flag gives this output:

 ` ` `
Geometry file(s) written in [HH:MM:SS]: 0:00:01
*** Error in `python3': free(): invalid size: 0x00007f422c54a010 ***
Aborted (core dumped)
 ` ` `

Neither of these errors show a segmentation fault, but that was occurring with the same commands earlier. I'm using Linux and python3. Please let me know if you need any more information, thanks.

**Comment by craig-warren** [comment] 2015-10-13 16:11
Looks to me like the simulation is completing successfully but Python is somehow not able to free up memory it has used. Have you checked to see if output (.out) and geometry (.vti) files are created and can be viewed? What Linux distro are you using and which version of Python 3?

**Comment by max-jacobs** [comment] 2015-10-13 16:19
The simulation may be completing successfully as the commands above do create the output (.out) and (.vti) files. However if I run the commands with the flag `-n 2`, the error occurs before the second iteration and so the simulation ends. Im using Ubuntu 14 and python 3.4.3.

**Comment by craig-warren** [comment] 2015-10-13 18:32
Yes, Python is unlikely to continue after the memory error. I'll need to investigate this more fully when I get back to the office (not for another week or so). One thing to try for now is to see whether the memory problem is related to (OpenMP) threading. Can you add the command ``#num_threads: 1`` to the input file and try again.

I also just fixed a bug that stopped rough surfaces getting properly created, so you may want to pull a new copy of the source. I don't think it is related to this issue though.

**Comment by max-jacobs** [comment] 2015-10-14 11:08
Ok, thanks. Just tried with the command '#num_threads: 1' and the same error is raised.

**Comment by craig-warren** [comment] 2015-10-14 20:41
Thanks. Yes it seems to not be related to OpenMP threading.

I have now reproduced the error on both Ubuntu 14.04 with Python 3.4.0 and Windows 7 (64-bit) with Python 3.5. As you say it is tied to the ``#fractal_box`` command. The error suggests Python is trying to free memory that has already been freed. I would think this is caused by C-code that is being generated by Cython, probably as a result of something strange in the ``#fractal_box`` command implementation. I'll keep looking...weird how it doesn't show up on the Mac.

**Comment by craig-warren** [comment] 2015-10-19 11:55
I think this should now be fixed, I found an out-of-bounds bug when writing voxels for the `#fractal_box` command. I have quickly checked, and the `heterogeneous_soil.in` model now seems to run OK on Windows and Linux. I'll close the issue for now, but let me know if you are stilling this this problem.

**Closed by craig-warren** 2015-10-19 11:55 UTC
